### ISSUE TITLE
When will you publish to NPM?

### ISSUE THREAD

**Issue by scottcorgan** [gooy/js-deco#2]
We've implemented a lot of these modules internally, but I'd like to get a single module that's open source to contribute to.

With that in mind, when will this be on NPM?

**Comment by Aaike** [comment]
oh i hadn't thought about publishing it to npm yet.
im the meantime you can install it though using npm install `gooy/es7-method-decorators`

**Comment by Aaike** [comment]
i'd like to get your thoughts though on renaming this repo before i publish it, i'm not totally comfortable with `es7-method-decorators`, much better would have been simply `js-method-decorators`.
Thoughts ?

**Comment by Aaike** [comment]
i have renamed the package to `js-deco` and published to npm , jspm and bower.
